export const SET_MATCH_DATA = "SET_MATCH_DATA";
export const SET_MATCH_DATA_SUCCESS = "SET_MATCH_DATA_SUCCESS";
export const SET_CURRENT_MATCH_ID = "SET_CURRENT_MATCH_ID";
export const GET_CURRENT_MATCH_DETAILS = "GET_CURRENT_MATCH_DETAILS";
export const UPDATED_OVER_PROGRESS_DATA = "UPDATED_OVER_PROGRESS_DATA";
export const SET_UPDATED_MATCH_DATA = "SET_UPDATED_MATCH_DATA";
